/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cart/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить корзину
         * @description Возвращает текущую корзину пользователя или гостя со всеми товарами и итоговой суммой.
         */
        get: operations["cart_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/clear/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Очистить корзину
         * @description Полностью удаляет все товары из корзины.
         */
        delete: operations["cart_clear_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Добавить товар в корзину
         * @description Добавляет товар в корзину. По умолчанию добавляется 1 штука, но можно указать нужное количество в поле `quantity`. Если товар уже есть в корзине, его количество увеличивается.
         */
        post: operations["cart_items_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cart/items/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Удалить товар из корзины
         * @description Удаляет одну единицу товара из корзины. Если передать параметр `?all=true`, удалятся все единицы этого товара.
         */
        delete: operations["cart_items_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cms/blocks/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description GET /api/cms/blocks/
         *     Возвращает все активные блоки главной страницы
         */
        get: operations["cms_blocks_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить всё меню
         * @description Возвращает все активные категории с их товарами и вариантами
         */
        get: operations["menu_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu/categories/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить список категорий
         * @description Возвращает все активные категории
         */
        get: operations["menu_categories_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/menu/products/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Получить товар
         * @description Возвращает детали одного товара с его вариантами
         */
        get: operations["menu_products_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `BANNER` - Промо-баннер
         *     * `CATEGORY_GRID` - Сетка категорий
         *     * `PRODUCT_CAROUSEL` - Карусель товаров
         * @enum {string}
         */
        BlockTypeEnum: "BANNER" | "CATEGORY_GRID" | "PRODUCT_CAROUSEL";
        Cart: {
            readonly id: number;
            /** Format: uuid */
            readonly session_id: string | null;
            readonly items: components["schemas"]["CartItem"][];
            /** Format: decimal */
            readonly total_price: string;
        };
        CartItem: {
            readonly id: number;
            product: number;
            readonly product_name: string;
            /** Format: decimal */
            readonly product_price: string;
            readonly product_image_url: string;
            quantity?: number;
            /** Format: decimal */
            readonly total_price: string;
        };
        /** @description Сериализатор для категорий — для списка меню */
        Category: {
            readonly id: number;
            /** Название категории */
            name: string;
        };
        Menu: {
            readonly id: number;
            /** Название категории */
            name: string;
            readonly products: components["schemas"]["Product"][];
        };
        PageBlock: {
            readonly id: number;
            /** Тип блока */
            block_type: components["schemas"]["BlockTypeEnum"];
            /**
             * Данные блока (JSON)
             * @description Для BANNER: {'title': '...', 'image_url': '...'} | Для CATEGORY_GRID: {'category_ids': [1, 2]}
             */
            payload?: unknown;
            /** Порядок отображения */
            sort_order?: number;
        };
        /** @description Сериализатор для товаров (используется внутри категории) */
        Product: {
            readonly id: number;
            /** Название товара */
            name: string;
            readonly category_name: string;
            readonly image: string;
            /** Описание / Состав */
            description?: string;
            /**
             * Вес (кг)
             * Format: decimal
             */
            weight?: string | null;
            /**
             * В наличии?
             * @description Отмечайте, если товар можно купить.
             */
            is_available?: boolean;
            /**
             * Цена
             * Format: decimal
             */
            price?: string;
            /**
             * Старая цена (для скидки)
             * Format: decimal
             * @description Если заполнено, на сайте будет отображаться как зачёркнутая цена
             */
            old_price?: string | null;
        };
        /** @description Детальный сериализатор для одного товара */
        ProductDetail: {
            readonly id: number;
            /** Название товара */
            name: string;
            /**
             * ID в r-keeper (RK7)
             * @description ID блюда в кассе. Не менять!
             */
            crm_id?: string | null;
            /** Слаг (URL) */
            slug?: string;
            readonly image: string;
            /** Описание / Состав */
            description?: string;
            /** Отображать в меню */
            is_active?: boolean;
            /** Количество */
            quantity?: number;
            /**
             * Вес (кг)
             * Format: decimal
             */
            weight?: string | null;
            /**
             * В наличии?
             * @description Отмечайте, если товар можно купить.
             */
            is_available?: boolean;
            /**
             * Цена
             * Format: decimal
             */
            price?: string;
            /**
             * Старая цена (для скидки)
             * Format: decimal
             * @description Если заполнено, на сайте будет отображаться как зачёркнутая цена
             */
            old_price?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cart_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Корзина успешно получена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cart"][];
                };
            };
        };
    };
    cart_clear_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Корзина успешно очищена */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cart_items_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /**
                     * @description ID продукта
                     * @example 5
                     */
                    product: number;
                    /**
                     * @description Количество (по умолчанию 1)
                     * @default 1
                     * @example 1
                     */
                    quantity?: number;
                };
            };
        };
        responses: {
            /** @description Товар успешно добавлен */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartItem"];
                };
            };
            /** @description Ошибка валидации */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cart_items_destroy: {
        parameters: {
            query?: {
                /** @description Если true, удаляет все единицы товара (по умолчанию false) */
                all?: boolean;
            };
            header?: never;
            path: {
                /** @description A unique integer value identifying this cart item. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Товар успешно удален */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Нельзя удалять товары из чужой корзины */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Товар не найден в корзине */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cms_blocks_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageBlock"][];
                };
            };
        };
    };
    menu_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Menu"][];
                };
            };
        };
    };
    menu_categories_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    menu_products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Slug товара (например: pepperoni, margarita) */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
        };
    };
}
